/**
 * WHO:
 *   Antigravity
 *   (Context: Gemini Debugger)
 *
 * WHAT:
 *   File watcher for the Gemini interaction loop.
 *   Captures ephemeral files (.tmp, .pb, .resolved) and markdown updates from the .gemini folder
 *   to analyze the agent's "brain" and thought process in real-time.
 *
 *   [Inputs]
 *   - Watches: /Users/laptop/.gemini/antigravity (recursively)
 *
 *   [Outputs]
 *   - Copies captured files to: ./captures/
 *   - Logs events to console.
 *
 *   [Side Effects]
 *   - File system I/O (copying files).
 *
 *   [How to run/invoke it]
 *   - node watcher.js
 *
 * WHEN:
 *   2025-12-03
 *   Last Modified: 2025-12-03
 *
 * WHERE:
 *   apps/gemini-debugger/watcher.js
 *
 * WHY:
 *   To debug and analyze the intermediate states and files generated by the Gemini agent,
 *   which are often deleted too quickly to inspect manually.
 */

const chokidar = require('chokidar');
const fs = require('fs');
const path = require('path');

// Configuration
const WATCH_DIR = '/Users/laptop/.gemini/antigravity';
const CAPTURE_DIR = path.join(__dirname, 'captures');

// Ensure capture directory exists
if (!fs.existsSync(CAPTURE_DIR)) {
  fs.mkdirSync(CAPTURE_DIR, { recursive: true });
}

console.log(`Starting Gemini Debugger...`);
console.log(`Watching: ${WATCH_DIR}`);
console.log(`Capturing to: ${CAPTURE_DIR}`);

// Initialize watcher
// We ignore initial add events to avoid copying thousands of existing files on startup
const watcher = chokidar.watch(WATCH_DIR, {
  ignored: [
    '**/node_modules/**' 
  ],
  persistent: true,
  ignoreInitial: true,
  depth: 5 // Watch subdirectories
});

watcher
  .on('add', (filePath) => handleFileEvent('ADD', filePath))
  .on('change', (filePath) => handleFileEvent('CHANGE', filePath));

function handleFileEvent(type, filePath) {
  const filename = path.basename(filePath);
  const ext = path.extname(filePath);

  // We are interested in .tmp, .pb, and .resolved files
  // Also brain markdown files as they change
  if (['.tmp', '.pb', '.resolved', '.md'].includes(ext) || filename.includes('.resolved')) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const safeFilename = filename.replace(/[^a-zA-Z0-9._-]/g, '_');
    const destPath = path.join(CAPTURE_DIR, `${timestamp}_${type}_${safeFilename}`);

    try {
      // Use copyFile for speed. If file is gone (deleted quickly), it might fail.
      fs.copyFile(filePath, destPath, (err) => {
        if (err) {
          if (err.code === 'ENOENT') {
            // File disappeared before we could copy it - common for .tmp files
            console.log(`[${type}] Missed ephemeral file: ${filename}`);
          } else {
            console.error(`[${type}] Error copying ${filename}:`, err.message);
          }
        } else {
          console.log(`[${type}] Captured: ${filename} -> ${path.basename(destPath)}`);
        }
      });
    } catch (e) {
      console.error(`[${type}] Exception handling ${filename}:`, e.message);
    }
  }
}

console.log('Watcher is ready. Trigger some IDE actions to see captures.');

